config/routes.rb
 Rails.application.routes.draw do
   
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get'/' =>'homes#top',as:'top'
    resources :customers,only: [:index, :show, :edit, :update,]
    # get 'customers/index'
    # get 'customers/show'
    # get 'customers/:id/edit'=> "customers#edit"
    # patch 'customers/:id'=> "customers#update"
    get 'genres/index'
    resources :genres,only: [:update, :edit,]
    resources :orders
    post 'genres/create'
  end

  scope module: :public do
    delete 'cart_items/destroy_all' =>"cart_items#destroy_all"
    resources :cart_items, only: [:destroy,:index,:update,:create]

  end


  get 'homes/top'


  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    get 'about' =>'homes#about'
    resources :items
    resources :orders,only:[:new,:index,:show,:create]
    post "/customers/orders/confirmation" => "orders#confirmation"
    get "customers/orders/completion" => "orders#completion"
   resources :customers,only:[:update]
    get '/customers/mypage' =>'customers#show'
    get "/customers/withdraw" => "customers#withdraw"

    patch "/customers/mypage" => "customers#update"
    get "/customers/mypage/edit" => "customers#edit"
    get "/customers/quit" => "customers#quit"
  end

  namespace :admin do
    resources :items
  end
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    user_name = last_name.to_s + first_name.to_s
    return user_name
  # id.to_s + email
    #id.to_s + "_"+ email
  # "test"
  end

   has_many :orders
   has_many :cart_items, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
   has_one_attached :image
   belongs_to :genre
   has_many :order_details
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_price
   (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
     @customers = Customer.page(params[:page])
  end

  def show
     @customers =Customer.find(params[:id])
  end
  def quit

  end

  def edit
     @customer = Customer.find(params[:id])
  end

  def update
     @customer = Customer.find(params[:id])
     if @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
     else
    render :edit
     end
  end

  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana, :first_name_kana,:email,:postal_code,:address,:telphone_number,:is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class  Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page])
  end

  def update
    @genres = Genre.find(params[:id])
  if @genres.update(genre_params)
    redirect_to admin_genres_index_path, notice: "Genre was successfully updated."
  else
    render :edit
  end
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
   if@genre.save
    redirect_to admin_genres_index_path
   end
  end
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
   @orders = Order.page(params[:page])
   @total_amount =0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
   @item = Item.new
  end

  def update


  end

  def show
   @item = Item.find(params[:id])
  end

  def index
   @items = Item.all.page(params[:page])
  end

  def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:image, :name,:introduction,:genre_id,:price,:is_active,)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
   @order = Order.find(params[:id])
   @customer = @order.customer
   @order_details = @order.order_details
   @subtotal =0
   @shipping_cost =800
  end

  def new
   @orders = order.new
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

   def after_sign_in_path_for(resource)
     admin_top_path
   end


   def after_sign_out_path_for(resource)
    admin_session_path
   end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admin/customers/edit.html.erb
<!--~さんの会員情報編集-->
<h1 class="font-weight-normal">会員情報編集</h1>


 <%= form_with model: @customer,url: admin_customer_path(@customer) do |f| %>
  <div class="field">
  </div>

  <div class="field">
    <%= f.label :last_name ,"氏名" %>
    <%= f.text_field :last_name %>
     <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name_kana, "(フリガナ)" %>
    <%= f.text_field :last_name_kana %>
    <%= f.text_field :first_name_kana %>
  </div>

  <div class="field">
    <%= f.label :postal_code, "(郵便番号)" %>
    <%= f.text_field :postal_code %>
  </div>

  <div class="field">
    <%= f.label :address, "(住所)" %>
    <%= f.text_field :address, autocomplete: "current-password" %>
  </div>

  <div class="field">
    <%= f.label :telphone_number, "(電話番号)" %>
    <%= f.text_field :telphone_number, autocomplete: "current-password" %>
  </div>

  <div class="field">
    <%= f.label :email,"(メールアドレス)" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
  <%= f.radio_button :is_deleted, :true %>
  <%= f.label :is_deleted, "退会", value: :true %>
  <%= f.radio_button :is_deleted, :false %>
  <%= f.label :is_deleted, "有効", value: :false %>
  </div>

 <%= f.submit '変更を保存' %>

<% end %>

app/views/admin/customers/index.html.erb
<h4><class="font-weight-normal">会員一覧</h4>

  <div class="col-md-8 offset-md-1">
     <table class="table table-hover table-inverse">
      <thead>
       <tr>
        <th>会員ID</th>
         <th>氏名</th>
          <th>メールアドレス</th>
           <th>ステータス</th>
            <th colspan="3"></th>
       </tr>
      </thead>

      <tbody>
       <% @customers.each do |customer| %>
        <tr>
         <td><%= customer.id %></td>
          <td><%= link_to customer.full_name,admin_customer_path(customer.id) %></td>
           <td><%= customer.email %></td>
        <%if customer.is_deleted==false %>
         <td>有効</td>
        <% else %>
         <td>退会</td>
        <% end %>
        </tr>
       <% end %>
       <%= paginate @customers %>

      </tbody>
    </table>
  </div>

app/views/admin/customers/show.html.erb
<h1>会員詳細</h1>

 <p>会員ID</p><%= @customers.id %>
  <p>氏名</p><%= @customers.full_name %>
   <p>フリガナ</p><%= @customers.last_name_kana %><%= @customers.first_name_kana %>
    <p>郵便番号</p><%= @customers.postal_code %>
     <p>住所</p><%= @customers.address %>
      <p>電話番号</p><%= @customers.telphone_number %>
       <p>メールアドレス</p><%= @customers.email %>

<% if @customers.is_deleted == true %>
 <p>無効</p>
<% else %>
 <p>有効</p>
<% end %>

<%=link_to "編集する",edit_admin_customer_path(@customers), class: "btn btn-success"%>
<%=link_to "注文履歴一覧を見る",admin_top_path,class:"btn btn-Primary" %>

app/views/admin/genres/edit.html.erb
<h4><class="font-weight-normal">ジャンル編集</h4>

<%= form_with model: @genre , url: admin_genre_path(@genre)  do |f| %>

 <div class="field">
    <%= f.label :ジャンル名 %>
    <%= f.text_field :name%>
 </div>

   <%= f.submit "変更を保存する" %>

<% end %>

app/views/admin/genres/index.html.erb
<h4><class="font-weight-normal">ジャンル一覧・追加</h4>

<%= form_with model: @genre , url: admin_genres_create_path  do |f| %>

 <div class="field">
    <%= f.label :name,"ジャンル名" %>
    <%= f.text_field :name, autofocus: true, autocomplete: "email" %>
 </div>

   <%= f.submit "新規登録" %>


<% end %>

<table class="table table-hover ">
      <thead>
       <tr>
        <th></th>
        <th>ジャンル</th>
        <th colspan="2"></th>
       </tr>
      </thead>

      <tbody>
       <% @genres.each do |genre| %>
        <tr>
         <td><%= genre.name %></td>
         <td><%=link_to "編集する",edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>

        </tr>

       <% end %>


      </tbody>
    </table>

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>

<%= form_with model: @item , url: admin_items_path  do |f| %>

  <div class="field">
   <%= f.label :商品画像 %>
   <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
   </div>

  <div class="field">
    <%= f.label :商品名 %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :商品説明 %>
    <%= f.text_area :introduction, autocomplete: "current-password" %>
  </div>

  <div class="field">
  <%= f.label :ブランド %>
  <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :税抜価格 %>
    <%= f.text_field :price, autocomplete: "current-password" %>円
  </div>

  <div class="field">
  <%= f.radio_button :is_active, :true %>
  <%= f.label :is_active, "販売中", value: :true %>
  <%= f.radio_button :is_active, :false %>
  <%= f.label :is_active, "販売停止中", value: :false %>
  </div>

   <%= f.submit "変更を保存" %>
 <% end %>

app/views/admin/items/index.html.erb
<div class="container">
<h2><class="font-weight-normal">商品一覧</h2>
 <div class="row">
  <% @items.each do |item| %>
   <div class="col-3">
    <%= link_to item_path(item.id) do %>
    <%= image_tag item.get_image(100,100), class:"card-img-top"; %>
    <p><%= link_to item.name,item_path(item.id) %></p>
    <% end %>
    ¥<%= item.price %>

   </div>
  <% end %>
  <%= paginate @items %>
 </div>
</div>

app/views/admin/items/new.html.erb
<h2>商品新規登録</h2>
<%= form_with model: @item , url: admin_items_new_path  do |f| %>

  <div class="field">
   <%= f.label :商品画像 %>
   <%= f.file_field :image, placeholder: "プロフィール画像", accept: "image/*" %>
   </div>

  <div class="field">
    <%= f.label :商品名 %>
    <%= f.text_field :name, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :商品説明 %>
    <%= f.text_area :introduction, autocomplete: "current-password" %>
  </div>

  <div class="field">
  <%= f.label :ジャンル %>
  <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :税抜価格 %>
    <%= f.text_field :price, autocomplete: "current-password" %>円
  </div>

  <div class="field">
  <%= f.radio_button :is_active, :true %>
  <%= f.label :is_active, "販売中", value: :true %>
  <%= f.radio_button :is_active, :false %>
  <%= f.label :is_active, "販売停止中", value: :false %>
  </div>

   <%= f.submit "新規登録" %>
 <% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>

<%= image_tag @item.get_image(200,200) %>
 <p>商品名</p><%= @item.name %>
  <p>商品説明</p><%= @item.introduction %>
   <p>ブランド</p><%= @item.genre.name %>
    <p>税込価格（税抜価格）</p><%= @item.add_tax_price %>円
     <p>販売ステータス</p>
     
<% if @item.is_active == true %>
<p>販売中</p>
<% else %>
 販売停止中
<% end %>

<%=link_to "編集する",edit_admin_item_path(@item), class: "btn btn-success"%>

app/views/admin/orders/show.html.erb
<h1>注文履歴詳細</h1>


 <%= form_with model: @order , url: customers_orders_confirmation_path  do |f| %>

  <h2>購入者</h2><%= @customer.full_name %>
  <h2>注文日</h2><%= @order.created_at.strftime('%Y/%m/%d') %>

  <div class="field">
    <h2>支払い方法</h2>
     <% if @order.payment_method ==0 %>
     <p>クレジットカード</p>
     <% else %>
     <p>銀行振込</p>
     <% end %>
  </div>

 <h2>配送先</h2>

  <%= "〒" %><%= @customer.postal_code %><%= @customer.address %><%= @customer.last_name %><%= @customer.first_name %>

 <% end %>

 <div class=container px-5 px-sm-0 >
  <div class="row" >

    <table class="table table-hover table-inverse">
      <thead>
       <tr>
        <th>商品名</th>
         <th>単価（税込）</th>
          <th>数量</th>
           <th>小計</th>



       </tr>
      </thead>

      <tbody>
       <% @order_details.each do |cart_item| %>
        <tr>
         <td><%= cart_item.item.name %></td>
          <td><%= cart_item.item.price %></td>
          <td><%= cart_item.amount %></td>
          <td>
           <%= cart_item.item.price* cart_item.amount %>
           <% @subtotal += cart_item.item.price* cart_item.amount %>
          </td>
         </tr>
        <% end %>


            <th>送料</th><td><%= @shipping_cost %></td>
             <th>商品合計</th><td><%= @subtotal %></td>
              <th>請求金額</th><td><%= @shipping_cost + @subtotal %></td>


      </tbody>
    </table>
 </div>
</div>