config/routes.rb
 Rails.application.routes.draw do
   
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get'/' =>'homes#top',as:'top'
    resources :customers,only: [:index, :show, :edit, :update,]
    # get 'customers/index'
    # get 'customers/show'
    # get 'customers/:id/edit'=> "customers#edit"
    # patch 'customers/:id'=> "customers#update"
    get 'genres/index'
    resources :genres,only: [:update, :edit,]
    resources :orders
    post 'genres/create'
  end

  scope module: :public do
    delete 'cart_items/destroy_all' =>"cart_items#destroy_all"
    resources :cart_items, only: [:destroy,:index,:update,:create]

  end


  get 'homes/top'


  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    get 'about' =>'homes#about'
    resources :items
    resources :orders,only:[:new,:index,:show,:create]
    post "/customers/orders/confirmation" => "orders#confirmation"
    get "customers/orders/completion" => "orders#completion"
   resources :customers,only:[:update]
    get '/customers/mypage' =>'customers#show'
    get "/customers/withdraw" => "customers#withdraw"

    patch "/customers/mypage" => "customers#update"
    get "/customers/mypage/edit" => "customers#edit"
    get "/customers/quit" => "customers#quit"
  end

  namespace :admin do
    resources :items
  end
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    user_name = last_name.to_s + first_name.to_s
    return user_name
  # id.to_s + email
    #id.to_s + "_"+ email
  # "test"
  end

   has_many :orders
   has_many :cart_items, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
   has_one_attached :image
   belongs_to :genre
   has_many :order_details
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_price
   (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class  Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page])
  end

  def update
    @genres = Genre.find(params[:id])
  if @genres.update(genre_params)
    redirect_to admin_genres_index_path, notice: "Genre was successfully updated."
  else
    render :edit
  end
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
   if@genre.save
    redirect_to admin_genres_index_path
   end
  end
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
   @orders = Order.page(params[:page])
   @total_amount =0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
   @item = Item.new
  end

  def update


  end

  def show
   @item = Item.find(params[:id])
  end

  def index
   @items = Item.all.page(params[:page])
  end

  def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:image, :name,:introduction,:genre_id,:price,:is_active,)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
   @order = Order.find(params[:id])
   @customer = @order.customer
   @order_details = @order.order_details
   @subtotal =0
   @shipping_cost =800
  end

  def new
   @orders = order.new
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
        <a class="navbar-brand" href="/"><span>LOGO</span></a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
         </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
 <% if admin_signed_in? %>


          <li>
           <%= link_to  admin_items_path, class:"nav-link text-light" do %>
          <i class="fas fa-items"></i> 商品一覧
          <% end %>
          </li>

           <li>
           <%= link_to  admin_customers_path,class:"nav-link text-light" do %>
           <i class="fas fa-home"></i> 会員一覧
           <% end %>

          <li>
            <%= link_to admin_top_path, class:"nav-link text-light" do %>
          <i class="fas/end "></i>注文履歴一覧
          <% end %>
          </li>

         <li>
          <%= link_to  admin_genres_index_path, class:"nav-link text-light" do %>
          <i class="fas fa-sign-out-alt"></i> ジャンル一覧
          <% end %>
           </li>

          <li>
           <%= link_to   destroy_admin_session_path,class:"nav-link text-light" ,method: :delete do %>
           <i class="fas fa-home"></i> ログアウト
           <% end %>
          </li>



 <% elsif customer_signed_in? %>
           <li>
           <%= link_to  customers_mypage_path,class:"nav-link text-light" do %>
           <i class="fas fa-home"></i> マイページ
           <% end %>

          </li>
          <li>
           <%= link_to  items_path, class:"nav-link text-light" do %>
          <i class="fas fa-items"></i> 商品一覧
          <% end %>
          </li>

          <li>
            <%= link_to cart_items_path, class:"nav-link text-light" do %>
          <i class="fas/end "></i>カート
          <% end %>
          </li>

         <li>
          <%= link_to   destroy_customer_session_path, class:"nav-link text-light",method: :delete do %>
          <i class="fas fa-sign-out-alt"></i> ログアウト

         <% end %>
          </li>


         <% else %>
           <li>
           <%= link_to  about_path,class:"nav-link text-light" do %>
           <i class="fas fa-home"></i> About
           <% end %>

          </li>
          <li>
           <%= link_to  items_path, class:"nav-link text-light" do %>
          <i class="fas fa-items"></i> 商品一覧
          <% end %>
          </li>

          <li>
            <%= link_to  new_customer_registration_path, class:"nav-link text-light" do %>
          <i class="fas/end "></i>新規会員登録
          <% end %>
          </li>

         <li>
          <%= link_to   new_customer_session_path, class:"nav-link text-light" do %>
          <i class="fas fa-sign-out-alt"></i> ログイン

         <% end %>
          </li>




        <% end %>
        </ul>
         </div>
       </div>
  </nav>
  <div class="d-flex flex-row ">

  </div>

<!--<div class="d-flex flex-row bd-highlight mb-3">-->
<!--  <div class="p-2 bd-highlight">Flex item 1</div>-->
<!--  <div class="p-2 bd-highlight">Flex item 2</div>-->
<!--  <div class="p-2 bd-highlight">Flex item 3</div>-->
<!--</div>-->






   </header>
    <%= yield %>
  </body>


 <footer>


 </footer>

</html>